ComponentDesign/Pages/About.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ComponentDesign.Pages
{
    public class AboutModel : PageModel
    {
        public string Message { get; set; }

        public void OnGet()
        {
            Message = "Your application description page.";
        }
    }
}

ComponentDesign/Pages/Contact.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ComponentDesign.Pages
{
    public class ContactModel : PageModel
    {
        public string Message { get; set; }

        public void OnGet()
        {
            Message = "Your contact page.";
        }
    }
}

ComponentDesign/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ComponentDesign.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

ComponentDesign/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ComponentDesign.Pages
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {

        }

        public async Task OnPostCartAppend(string myVar)
        {
            Program.count++;
            var addItem = Program.menu.findItem(myVar);
            Program.cart.insertItem(addItem);
            Program.cartTotal += addItem.Price;
        }


        public async Task OnPostCartRemove(string myVar)
        {
            Program.count--;
            var addItem = Program.menu.findItem(myVar);
            Program.cart.removeItem(addItem);
            Program.cartTotal -= addItem.Price;
            if (Program.cartTotal < 0)
                Program.cartTotal = 0;
        }

    }
}

ComponentDesign/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ComponentDesign.Pages
{
    public class PrivacyModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

ComponentDesign/Pages/About.cshtml
@page
@model AboutModel
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@Model.Message</h3>

<p>Use this area to provide additional information.</p>

ComponentDesign/Pages/Contact.cshtml
@page
@model ContactModel
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@Model.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

ComponentDesign/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";

}

<div id="menu-cart-ctn">

    <div id="menu" class="items">
        <div style="display:inline;">
            <h2 style="text-align: center">Menu</h2>
            @foreach (var item in Program.menu.getMenu())
            {
                <div class="menu-item" style=" border: 1px solid black; border-radius: 25px; padding:30px; margin-bottom: 5px;">
                    <div style="text-align: justify; display: inline;">
                        <h3 style="display: inline-block">@item.Name</h3>
                        <p style="display: inline-block; margin-left: 10px;">@item.Price</p>
                    </div>
                    <p>@item.Description</p>

                    <form asp-page-handler="CartAppend" asp-route-myVar="@item.Name" method="post">
                        <button class="btn btn-default">Add To Cart</button>


                    </form>
                </div>

            }
        </div>
    </div>

    <div class="items" id="cart">
        <h2 style="text-align: center">Items in Cart: @Program.cart.NumOfItems</h2>
        @if (Program.cart.NumOfItems > 0)
        {

            @foreach (var item in Program.cart.getMenu())
            {
                <div class="menu-item" style=" border: 1px solid black; border-radius: 25px; padding:30px; margin-bottom: 5px;">
                    <div style="text-align: justify; display: inline;">
                        <h3 style="display: inline-block">@item.Name</h3>
                        <p style="display: inline-block; margin-left: 10px;">@item.Price</p>
                    </div>
                    <form asp-page-handler="CartRemove" asp-route-myVar="@item.Name" method="post">
                        <button class="btn btn-default">Remove from Cart</button>
                    </form>

                </div>

            }
        }
        <h2>Cart Total: @Program.cartTotal</h2>
    </div>
</div> <!-- end ctn-->

ComponentDesign/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ComponentDesign</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/css/style.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>


    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>